LineLength:
  Description: 'Limit lines to 120 characters.'
  Max: 120

Blocks:
  Description: >-
                Avoid using {...} for multi-line blocks (multiline chaining is
                always ugly).
                Prefer {...} over do...end for single-line blocks.
  Enabled: false